version: 2

multi-ecosystem-groups:
  automation:
    schedule:
      interval: weekly
      day: friday
      time: "08:00"
      timezone: Europe/Madrid
    target-branch: development
    labels:
      - dependencies
      - ci-cd
    commit-message:
      prefix: "chore(deps)"

updates:
  - package-ecosystem: github-actions # GitHub Actions.
    directory: /
    patterns:
      - "*"
    cooldown:
      default-days: 7 # Retraso para prevenir supply-chain attack.
    open-pull-requests-limit: 1
    multi-ecosystem-group: automation

  - package-ecosystem: pre-commit # Pre-Commit.
    directory: /
    patterns:
      - "*"
    cooldown:
      default-days: 7 # Retraso para prevenir supply-chain attack.
    open-pull-requests-limit: 1
    multi-ecosystem-group: automation
