import os

OLLAMA_URL = os.environ["OLLAMA_URL"]
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "phi4:14b")
OLLAMA_KEEP_ALIVE = os.getenv("OLLAMA_KEEP_ALIVE")
OLLAMA_TIMEOUT = 120.0
OLLAMA_STARTUP_CHECK_TIMEOUT = 10.0
OLLAMA_PS_TIMEOUT = 10.0
OLLAMA_UNLOAD_TIMEOUT = 30.0
OLLAMA_TEMPERATURE = 0.2
OLLAMA_NUM_CTX = 8192
