export const ACRONIMOS: Record<string, string> = {
  AGPL: 'GNU Affero General Public License',
  API: 'Application Programming Interface',
  BM25: 'Best Match 25',
  BSD: 'Berkeley Software Distribution',
  BSL: 'Business Source License',
  CD: 'Continuous Deployment',
  CI: 'Continuous Integration',
  CPU: 'Central Processing Unit',
  CRUE: 'Conferencia de Rectores de las Universidades Españolas',
  CSRF: 'Cross-Site Request Forgery',
  CUDA: 'Compute Unified Device Architecture',
  cuDNN: 'CUDA Deep Neural Network',
  E2E: 'End-to-End',
  FK: 'Foreign Key',
  GPU: 'Graphics Processing Unit',
  HNSW: 'Hierarchical Navigable Small World',
  HTML: 'HyperText Markup Language',
  IA: 'Inteligencia artificial',
  IEC: 'International Electrotechnical Commission',
  IEEE: 'Institute of Electrical and Electronics Engineers',
  ISC: 'Internet Software Consortium',
  ISO: 'International Organization for Standardization',
  LGPL: 'GNU Lesser General Public License',
  LLM: 'Large Language Model',
  MIT: 'Massachusetts Institute of Technology',
  ML: 'Machine Learning',
  MVP: 'Minimum Viable Product',
  OCR: 'Optical Character Recognition',
  OFL: 'Open Font License',
  OSS: 'Open Source Software',
  PDF: 'Portable Document Format',
  PK: 'Primary Key',
  PWA: 'Progressive Web App',
  QA: 'Quality Assurance',
  RAG: 'Retrieval-Augmented Generation',
  ReDoS: 'Regular Expression Denial of Service',
  RRF: 'Reciprocal Rank Fusion',
  RSAL: 'Redis Source Available License',
  SaaS: 'Software as a Service',
  SSPL: 'Server Side Public License',
  TDD: 'Test-Driven Development',
  TTS: 'Text-To-Speech',
  UML: 'Unified Modeling Language',
  WCAG: 'Web Content Accessibility Guidelines',
  XSS: 'Cross-Site Scripting',
};
