export const ACRONIMOS: Record<string, string> = {
  CI:   'Continuous Integration',
  CRUE: 'Conferencia de Rectores de las Universidades Españolas',
  CSRF: 'Cross-Site Request Forgery',
  CUDA: 'Compute Unified Device Architecture',
  E2E:  'End-to-End',
  GPU:  'Graphics Processing Unit',
  HTML: 'HyperText Markup Language',
  IA:   'Inteligencia artificial',
  LLM:  'Large Language Model',
  MVP:  'Minimum Viable Product',
  OCR:  'Optical Character Recognition',
  OSS:  'Open Source Software',
  PWA:  'Progressive Web App',
  RAG:  'Retrieval-Augmented Generation',
  SaaS: 'Software as a Service',
  TDD:  'Test-Driven Development',
  TTS:  'Text-To-Speech',
};
